### ISSUE TITLE
Odyssey scraper too fast in Linux; update code to wait for page to be clickable

### ISSUE THREAD

**Issue by justinmayo** [biglocalnews/court-scraper#55]
stanford@stanford-dj-vbox:~$ court-scraper search --with-browser --place-id ga_dekalb --search-term 19D67383
Executing search for ga_dekalb
Traceback (most recent call last):
  File "/home/stanford/.pyenv/versions/3.7.6/bin/court-scraper", line 11, in <module>
    load_entry_point('court-scraper==0.1.0', 'console_scripts', 'court-scraper')()
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/cli.py", line 85, in search
    results = runner.search(**kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/runner.py", line 64, in search
    data = site.search(search_terms=search_terms, headless=headless)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/site.py", line 50, in search
    results_page.back_to_search_results()
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/pages/search_results.py", line 125, in back_to_search_results
    SearchResultsPageLocators.CASE_RESULTS_TAB
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/pages/search_results.py", line 134, in _locate_and_click
    self.driver.find_element(*locator).click()
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="tcControllerLink_1" href="#tcBody_1" class="ui-tabs-anchor" role="presentation" tabindex="-1">...</a> is not clickable at point (378, 27). Other element would receive the click: <div class="product">...</div>
  (Session info: chrome=89.0.4389.82)

**Comment by zstumgoren** [comment]
@justinmayo My hunch is that this was related to the window sizing issue when running headless, as opposed to the rate of loading page elements. Going to close this for now, but feel free to re-open with a comment if you're still seeing this bug
