### ISSUE TITLE
case_info.standard_data returns attribute error 

### ISSUE THREAD

**Issue by justinmayo** [biglocalnews/court-scraper#56]
Traceback (most recent call last):
  File "odyssey_indexer.py", line 82, in <module>
    main()
  File "odyssey_indexer.py", line 58, in main
    case = result.standard_data
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/case_info.py", line 43, in standard_data
    'place_id': self.place_id,
AttributeError: 'CaseInfo' object has no attribute 'place_id'

**Comment by zstumgoren** [comment]
`standard_data` has been refactored to be a bit more flexible, although `place_id` should generally be passed to `CaseInfo` and therefore will leave this as an expectation of `standard_data` for now
