### ISSUE TITLE
Odyssey scraper ValueError returned for some cases metadata

### ISSUE THREAD

**Issue by justinmayo** [biglocalnews/court-scraper#69]
stanford@stanford-dj-vbox:~/code/court-scraper-etl$ court-scraper search --place-id ga_dekalb --search-term 20D00023

Executing search for ga_dekalb
Traceback (most recent call last):
  File "/home/stanford/.pyenv/versions/3.7.6/bin/court-scraper", line 11, in <module>
    load_entry_point('court-scraper==0.1.0', 'console_scripts', 'court-scraper')()
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/cli.py", line 85, in search
    results = runner.search(**kwargs)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/runner.py", line 63, in search
    data = site.search(search_terms=search_terms)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/site.py", line 44, in search
    row_data = case_row.metadata
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/pages/search_results.py", line 69, in metadata
    field.strip() for field in self.inner_text.split('\t')
ValueError: not enough values to unpack (expected 5, got 1)

**Comment by justinmayo** [comment]
@zstumgoren This is the error I discovered when running my indexer script for 2020. Right now I am handling these with a try/except statement in the code, which seems to be working. But I'm seeing more that just the example case above with the same issue.

**Comment by zstumgoren** [comment]
Note this error only occurs when running "headless". Running with a browser enabled works fine:

```
court-scraper search --with-browser --place-id ga_dekalb --search-term 20D00023
```

**Comment by zstumgoren** [comment]
Selenium returns different ["inner text" for a SearchResultRow](https://github.com/biglocalnews/court-scraper/blob/master/court_scraper/platforms/odyssey_site/pages/search_results.py#L69) depending on context. 

We'll need more nuanced handling to deal with the scenarios below:

```
# headless has no tab character, only newlines
Br
'20D00023\nYvonne Lindsay VS CATRIEA ROBERTSON,EVETTE BLUKER\n01/02/2020Administratively ClosedROBERTSON, CATRIEA'

# browser-enabled has tab and newlines AND the ordering of \t\n is inconsistent
'20D00023\t\nYvonne Lindsay VS CATRIEA ROBERTSON,EVETTE BLUKER\n\t01/02/2020\tAdministratively Closed\tROBERTSON, CATRIEA'
```
