### ISSUE TITLE
Odyssey scraper AttributeError: NoneType object has no attribute 'click'

### ISSUE THREAD

**Issue by justinmayo** [biglocalnews/court-scraper#70]
Traceback (most recent call last):
  File "odyssey_indexer.py", line 209, in <module>
    main(place_id, year)
  File "odyssey_indexer.py", line 123, in main
    results = site.search(search_terms=batch, case_details=False)
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/site.py", line 33, in search
    portal_page.go_to_smart_search()
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/pages/portal.py", line 20, in go_to_smart_search
    self._click_port_button('smart_search')
  File "/home/stanford/.pyenv/versions/3.7.6/lib/python3.7/site-packages/court_scraper/platforms/odyssey_site/pages/portal.py", line 36, in _click_port_button
    button.click()
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by justinmayo** [comment]
@zstumgoren This error occurred after my indexer script had run through 685 case numbers. I tried to recreate this by just running the case numbers after 685 but the error did not return...
