### ISSUE TITLE
Add Napa County cli support

### ISSUE THREAD

**Issue by DiPierro** [biglocalnews/court-scraper#79]
Napa County, CA uses Odyssey: https://portal.napa.courts.ca.gov/Secure/Home/Dashboard/29

- [x] Add Napa to sites_meta.csv in order to expose via CLI

**Comment by ericjohannes** [comment]
I added two lines to sites_meta.csv:
ca,napa,odyssey_site,1,,https://portal.napa.courts.ca.gov/Secure/Home/Dashboard/29
ca,sonoma,odyssey_site,1,True,https://cmsportal.sonomacourt.org/IPortal/Home/Dashboard/26

run
court-scraper search   --place-id ca_napa   --search-term car*  --with-browser

Get this error:
Caching file: /Users/eblom/gits/ca-court-scraper/.court-scraper/cache/ca_napa/03/08/2021.html
Traceback (most recent call last):
  File "/Users/eblom/anaconda3/bin/court-scraper", line 10, in <module>
    sys.exit(cli())
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/court_scraper/cli.py", line 86, in search
    runner.cache_detail_pages(results)
  File "/Users/eblom/anaconda3/lib/python3.7/site-packages/court_scraper/runner.py", line 89, in cache_detail_pages
    with open(outfile, 'w') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eblom/gits/ca-court-scraper/.court-scraper/cache/ca_napa/03/08/2021.html'

Since I use the --with-browser flag I can see the browser open and searches seem to go well. I think it's using the date of a filing to create a file name and the slashes cause a problem.

**Comment by zstumgoren** [comment]
@ericjohannes There may be a few potential issues here. One is that our OdysseySite scraper is currently tuned to expect one or more case IDs, rather than a glob-based search term. The CLI in that respect is a little deceptive, since its interface suggests full support for any type of search term. We do hope to eventually support glob-style searches, but that will require adding support for [paged search results](https://github.com/biglocalnews/court-scraper/issues/11).

The glob-based search term in your example (`car*`) yields a search results page that appears to be structured differently than what you get when searching for a single case ID. I suspect that is related to the breakage you're seeing. In order to handle this, we'd likely need to expand our ability to scrape search result pages with multiple nested results. 

Let's chat offline so we can better understand your project's needs and determine a plan of attack.
